# ./config/auth0.yml
development:
  auth0_domain: <%= ENV['AUTH0_DOMAIN'] %>
  auth0_client_id: <%= ENV['AUTH0_CLIENT_ID'] %>
  auth0_client_secret: <%= ENV['AUTH0_CLIENT_SECRET'] %>
  auth0_callback_path: <%= ENV['AUTH0_CALLBACK_PATH'] %>
  auth0_audience: <%= ENV['AUTH0_AUDIENCE'] %>
